[default_session]
startup_command = "k"

[[session]]
name = "Dotfiles âš™ï¸"
path = "~/.dotfiles"
startup_command = "nvim ."

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "k"

[[session]]
name = "vogelino-portfolio"
path = "~/repos/vogelino-portfolio"
startup_command = "tms ~/repos/vogelino-portfolio"

[[session]]
name = "a-roh"
path = "~/repos/a-roh"
startup_command = "tms ~/repos/a-roh"


